commands matching guest hierchy: veewee, basebox, instance

diff --git a/bin/basebox b/bin/basebox
--- a/bin/basebox
+++ b/bin/basebox
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 #/ NAME
-#/     build-box -- build and export a vagrant basebox
+#/     box -- builds and boxes a vagrant
 #/
 #/ SYNOPSIS
-#/     build-box [veewee]
+#/     box [veewee] [basebox]
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -17,32 +17,28 @@ require 'bundler'
 # entry point
 function main {
   if [[ "$#" < 1 ]]; then
+    logger_fatal "missing vagrant"
+    exit 1
+  fi
+
+  if [[ "$#" < 2 ]]; then
     logger_fatal "missing veewee definition"
     exit 1
   fi
 
   local nm_veewee=$1; shift
+  local nm_basebox=$1; shift
 
   bundle_macports
 
-  local vbox_gui=""
-  if [[ "$FLAGS_gui" = "$FLAGS_FALSE" ]]; then
-    vbox_gui="-n"
-  fi
-  bundle exec vagrant basebox build $nm_veewee -f $FLAGS_gui
-
-  bundle exec vagrant basebox export $nm_veewee
-  mv $nm_veewee.box $shome/boxes/
-
-  bundle exec vagrant box remove $nm_veewee 2>&1 || VBoxManage unregistervm $nm_veewee --delete || true
-  bundle exec vagrant box add $nm_veewee $shome/boxes/$nm_veewee.box
-
-  VBoxManage unregistervm "$nm_veewee" --delete
+  $shome/bin/instance "$nm_basebox" "$nm_veewee"
+  $shome/bin/package "$nm_basebox"
+  bin/vagrant -- "$nm_basebox" destroy -f
 }
 
 # define command line options:
 #   var name, default, description, short option
-DEFINE_boolean 'gui' "$FLAGS_TRUE" 'guest is run with a GUI'
+DEFINE_string 'ip' '' 'ip addresses'
 
 # parse the command-line
 parse_command_line "$@" || exit $?
