guest inheritance is veewee, basebox, vagrant

diff --git a/bin/basebox b/bin/basebox
--- a/bin/basebox
+++ b/bin/basebox
@@ -4,7 +4,7 @@
 #/     build-box -- build and export a vagrant basebox
 #/
 #/ SYNOPSIS
-#/     build-box [definition]
+#/     build-box [veewee]
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -16,7 +16,12 @@ require 'bundler'
 
 # entry point
 function main {
-  nm_base=$1; shift
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing veewee definition"
+    exit 1
+  fi
+
+  local nm_veewee=$1; shift
 
   bundle_macports
 
@@ -24,15 +29,15 @@ function main {
   if [[ "$FLAGS_gui" = "$FLAGS_FALSE" ]]; then
     vbox_gui="-n"
   fi
-  bundle exec vagrant basebox build $nm_base -f $FLAGS_gui
+  bundle exec vagrant basebox build $nm_veewee -f $FLAGS_gui
 
-  bundle exec vagrant basebox export $nm_base
-  mv $nm_base.box $shome/boxes/
+  bundle exec vagrant basebox export $nm_veewee
+  mv $nm_veewee.box $shome/boxes/
 
-  bundle exec vagrant box remove $nm_base 2>&1 || VBoxManage unregistervm $nm_base --delete || true
-  bundle exec vagrant box add $nm_base $shome/boxes/$nm_base.box
+  bundle exec vagrant box remove $nm_veewee 2>&1 || VBoxManage unregistervm $nm_veewee --delete || true
+  bundle exec vagrant box add $nm_veewee $shome/boxes/$nm_veewee.box
 
-  VBoxManage unregistervm "$nm_base" --delete
+  VBoxManage unregistervm "$nm_veewee" --delete
 }
 
 # define command line options:
@@ -42,11 +47,6 @@ DEFINE_boolean 'gui' "$FLAGS_TRUE" 'guest is run with a GUI'
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
-
-if [[ "$#" < 1 ]]; then
-  logger_fatal "missing veewee definition"
-  exit 1
-fi
 
 # pass arguments to entry point
 main "$@"
diff --git a/bin/box b/bin/box
--- a/bin/box
+++ b/bin/box
@@ -4,7 +4,7 @@
 #/     box -- builds and boxes a vagrant
 #/
 #/ SYNOPSIS
-#/     box [vagrant] [veewee]
+#/     box [veewee] [basebox]
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -16,14 +16,24 @@ require 'bundler'
 
 # entry point
 function main {
-  nm_instance=$1; shift
-  nm_base=$1; shift
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing vagrant"
+    exit 1
+  fi
+
+  if [[ "$#" < 2 ]]; then
+    logger_fatal "missing veewee definition"
+    exit 1
+  fi
+
+  local nm_veewee=$1; shift
+  local nm_basebox=$1; shift
 
   bundle_macports
 
-  $shome/bin/instance "$nm_instance" "$nm_base"
-  $shome/bin/package "$nm_instance"
-  bin/vagrant -- "$nm_instance" destroy -f
+  $shome/bin/instance "$nm_basebox" "$nm_veewee"
+  $shome/bin/package "$nm_basebox"
+  bin/vagrant -- "$nm_basebox" destroy -f
 }
 
 # define command line options:
@@ -33,16 +43,6 @@ DEFINE_string 'ip' '' 'ip addresses'
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
-
-if [[ "$#" < 1 ]]; then
-  logger_fatal "missing vagrant"
-  exit 1
-fi
-
-if [[ "$#" < 2 ]]; then
-  logger_fatal "missing veewee definition"
-  exit 1
-fi
 
 # pass arguments to entry point
 main "$@"
