buildbox is meaty

diff --git a/bin/build-box b/bin/build-box
--- a/bin/build-box
+++ b/bin/build-box
@@ -1,14 +1,46 @@
-#!/bin/bash -e
+#!/bin/bash
 
-nm_base=$1; shift
-bin/bundler
+#/ NAME
+#/     build-media-ubuntu -- download and unpack ubuntu iso
+#/
+#/ SYNOPSIS
+#/     build-media-ubuntu [definition]
 
-figlet "build box"
-bundle exec vagrant basebox build $nm_base -f -n
+# figure out the project root under which bin, lib live
+shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
 
-figlet "exporting box"
-bundle exec vagrant basebox export $nm_base
-cp $nm_base.box definitions/$nm_base/
-rm -f $nm_base.box
+# load a meat library
+source "$shome/bin/_prime" "$@"
+source $shome/.profile
 
-bin/setup-box $nm_base
+# entry point
+function main {
+  nm_base=$1; shift
+
+  $shome/bin/bundler
+
+  figlet "build box"
+  bundle exec vagrant basebox build $nm_base -f -n
+
+  figlet "exporting box"
+  bundle exec vagrant basebox export $nm_base
+  cp $nm_base.box $shome/definitions/$nm_base/
+  rm -f $nm_base.box
+
+  $shome/bin/setup-box $nm_base
+}
+
+# define command line options:
+#   var name, default, description, short option
+
+# parse the command-line
+parse_command_line "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+if [[ "$#" < 1 ]]; then
+  logger.fatal "missing veewee definition"
+  exit 1
+fi
+
+# pass arguments to entry point
+main "$@"
