config ssh shows vagrants ssh config with their host only ip addresses

diff --git a/bin/config b/bin/config
--- a/bin/config
+++ b/bin/config
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 #/ NAME
-#/     config -- builds a vagrant basebox, box, or instance
+#/     config -- emits configuration for vagrants
 #/
 #/ SYNOPSIS
-#/     config [vagrant]
+#/     config ssh
 
 # figure out the project root under which bin, lib live
 shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
@@ -12,26 +12,54 @@ shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
 # load a meat library
 source "$shome/bin/_prime" "$@"
 require 'profile'
+require 'bundler'
 
 # entry point
 function main {
-  nm_box=$1; shift
-  
-  bundle exec chef-solo -c "config/solo.rb" -N "$nm_box"
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing component"
+    exit 1
+  fi
+
+  bundle_macports
+
+  local nm_component=$1; shift
+  case "$nm_component" in
+    ssh)
+      config_ssh "$@"
+      ;;
+    *)
+      logger_fatal "dont know how to handle component $nm_component"
+      exit 1
+      ;;
+  esac
+}
+
+function config_ssh {
+  set +f
+  local a
+  for a in $shome/vagrant/*; do 
+    if [[ ! -d "$a" ]]; then
+      break
+    fi
+
+    local nm_vagrant="$(basename "$a")"
+    local ip_vagrant="$(ryaml "$a/vagrant.yml" network)"
+cat <<EOF
+Host $nm_vagrant
+  HostKeyAlias $nm_vagrant.vagrant
+  Hostname $ip_vagrant
+EOF
+  done
+  set -f
 }
 
 # define command line options:
 #   var name, default, description, short option
-DEFINE_string 'ip' '' 'ip addresses'
 
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
-
-if [[ "$#" < 1 ]]; then
-  logger_fatal "missing vagrant"
-  exit 1
-fi
 
 # pass arguments to entry point
 main "$@"
