new instances can delete the old one configuring the instance won't destroy the .vagrant state file

diff --git a/bin/instance b/bin/instance
--- a/bin/instance
+++ b/bin/instance
@@ -16,15 +16,29 @@ require 'bundler'
 
 # entry point
 function main {
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing vagrant"
+    exit 1
+  fi
+
+  if [[ "$#" < 2 ]]; then
+    logger_fatal "missing veewee definition"
+    exit 1
+  fi
+
   nm_instance=$1; shift
   nm_base=$1; shift
 
   bundle_macports
 
   # check if the instance is already configured
-  if [[ -d "$shome/vagrant/$nm_instance" ]]; then
-    logger_fatal "$nm_instance already exists, not recreating"
-    exit 1
+  if [[ -f "$shome/vagrant/$nm_instance/.vagrant" ]]; then
+    if [[ "$FLAGS_delete" = "$FLAGS_FALSE" ]]; then
+      logger_fatal "$nm_instance already exists, not recreating"
+      exit 1
+    else
+      $shome/bin/vagrant -- "$nm_instance" destroy -f 
+    fi
   fi
 
   # copy vagrant templates
@@ -36,7 +50,7 @@ function main {
   else
     vagrant_source="$shome/definitions/$nm_instance/."
   fi
-  rsync --delete -ia "$vagrant_source"  "$shome/vagrant/$nm_instance/"
+  rsync --delete -ia --exclude .vagrant "$vagrant_source"  "$shome/vagrant/$nm_instance/"
 
   # configure Vagrantfile
   tmp_vagrantfile="$(mktemp -t XXXXXXXXX)"
@@ -70,20 +84,11 @@ function main {
 # define command line options:
 #   var name, default, description, short option
 DEFINE_string 'ip' '' 'ip addresses'
+DEFINE_boolean 'delete' "$FLAGS_FALSE" 'delete the instance if it exists'
 
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
-
-if [[ "$#" < 1 ]]; then
-  logger_fatal "missing vagrant"
-  exit 1
-fi
-
-if [[ "$#" < 2 ]]; then
-  logger_fatal "missing veewee definition"
-  exit 1
-fi
 
 # pass arguments to entry point
 main "$@"
