got rid of basebox, veewee does everything

diff --git a/bin/instance b/bin/instance
--- a/bin/instance
+++ b/bin/instance
@@ -45,15 +45,26 @@ function main {
 
   # copy vagrant templates
   local vagrant_source
-  if [[ -d $shome/definitions/$nm_basebox/vagrant ]]; then
-    vagrant_source="$shome/definitions/$nm_basebox/vagrant/."
-  elif [[ -f $shome/definitions/$nm_basebox/Vagrantfile ]]; then
-    vagrant_source="$shome/definitions/$nm_basebox/."
+  if [[ -n "$FLAGS_vagrant" ]]; then
+    if [[ -f $shome/definitions/$FLAGS_vagrant/Vagrantfile ]]; then
+      vagrant_source="$shome/definitions/$FLAGS_vagrant"
+    else
+      logger_fatal "cannot find a Vagrantfile for $FLAGS_vagrant"
+      exit 1
+    fi
   else
-    vagrant_source="$shome/definitions/$nm_instance/."
+    if [[ -f $shome/definitions/$nm_basebox/Vagrantfile ]]; then
+      vagrant_source="$shome/definitions/$nm_basebox"
+    elif [[ -f $shome/definitions/$nm_instance/Vagrantfile ]]; then
+      vagrant_source="$shome/definitions/$nm_instance"
+    else
+      logger_fatal "cannot find a Vagrantfile for $nm_basebox or $nm_instance"
+      exit 1
+    fi
   fi
+
   mkdir -p "$shome/vagrant"
-  rsync --delete -ia --exclude .vagrant "$vagrant_source"  "$shome/vagrant/$nm_instance/"
+  rsync --delete -ia --exclude .vagrant "$vagrant_source/."  "$shome/vagrant/$nm_instance/"
 
   # configure Vagrantfile
   tmp_vagrantfile="$(mktemp -t XXXXXXXXX)"
@@ -93,6 +104,7 @@ function main {
 DEFINE_string 'ip' '' 'ip addresses'
 DEFINE_boolean 'delete' "$FLAGS_FALSE" 'delete the instance if it exists'
 DEFINE_boolean 'reconfig' "$FLAGS_FALSE" 'reconfigure the instance'
+DEFINE_string 'vagrant' "" 'Vagrant configuration' 
 
 # parse the command-line
 parse_command_line "$@" || exit $?
diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -17,8 +17,17 @@ require 'bundler'
 
 # entry point
 function main {
-  nm_instance=$1; shift
-  nm_base=$1; shift
+  if [[ "$#" < 1 ]]; then
+    logger_fatal "missing vagrant"
+    exit 1
+  fi
+
+  if [[ "$#" < 2 ]]; then
+    set -- "$@" "$1"
+  fi
+
+  local nm_instance=$1; shift
+  local nm_base=$1; shift
 
   bundle_macports
 
@@ -27,23 +36,21 @@ function main {
 
   bundle exec vagrant box remove $nm_base 2>&1 || VBoxManage unregistervm $nm_base --delete || true
   bundle exec vagrant box add $nm_base $shome/boxes/$nm_base.box
+
+  if [[ "$FLAGS_destroy" = "$FLAGS_TRUE" ]]; then
+    $shome/bin/vagrant -- "$nm_instance" destroy -f
+  fi
 }
 
 # define command line options:
 #   var name, default, description, short option
+DEFINE_boolean "destroy" "$FLAGS_FALSE" "destroy the vm after packaging"
 
 # parse the command-line
 parse_command_line "$@" || exit $?
 eval set -- "${FLAGS_ARGV}"
 
-if [[ "$#" < 1 ]]; then
-  logger_fatal "missing vagrant"
-  exit 1
-fi
-
-if [[ "$#" < 2 ]]; then
-  set -- "$@" "$1"
-fi
-
 # pass arguments to entry point
 main "$@"
+
+
