boxes are now in vault

diff --git a/bin/setup-box b/bin/setup-box
--- a/bin/setup-box
+++ b/bin/setup-box
@@ -1,8 +1,40 @@
-#!/bin/bash -e
+#!/bin/bash
 
-nm_base=$1; shift
-bin/bundler
+#/ NAME
+#/     setup-box -- import a basebox into vagrant
+#/
+#/ SYNOPSIS
+#/     setup-box [definition]
 
-figlet "importing box"
-bundle exec vagrant box remove $nm_base 2>&1 || VBoxManage unregistervm $nm_base --delete || true
-bundle exec vagrant box add $nm_base definitions/$nm_base/$nm_base.box
+# figure out the project root under which bin, lib live
+shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"
+
+# load a meat library
+source "$shome/bin/_prime" "$@"
+source $shome/.profile
+
+# entry point
+function main {
+  nm_base=$1; shift
+
+  $shome/bin/bundler
+
+  figlet "importing box"
+  bundle exec vagrant box remove $nm_base 2>&1 || VBoxManage unregistervm $nm_base --delete || true
+  bundle exec vagrant box add $nm_base $shome/boxes/$nm_base.box
+}
+
+# define command line options:
+#   var name, default, description, short option
+
+# parse the command-line
+parse_command_line "$@" || exit $?
+eval set -- "${FLAGS_ARGV}"
+
+if [[ "$#" < 1 ]]; then
+  logger.fatal "missing veewee definition"
+  exit 1
+fi
+
+# pass arguments to entry point
+main "$@"
